version: '3.2'
services:
    mysql:
        image: mysql
        volumes:
            - ./database:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=123456789
        container_name: mysql
